version: '3.8'

services:
  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
  admin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: edzamo@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: edzamo