server:
  port: 9001
  servlet:
    context-path: /groovy-demo/api


## call a to profiles
#spring.profiles.active=dev
###@Profile. https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-profiles
