# vi docker-compose.yml
version: '3.3'
services:
    mongo:
        image: mongo:4.4
        ports:
            - '27017:27017'
        container_name: db_mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongoadmin
            - MONGO_INITDB_ROOT_PASSWORD=admin
        volumes:
            - ./mongo_data:/data/db


