server:
  port: 8092
spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/db
    username: user
    password: password
    pool:
      initial-size: 100
      max-size: 500
      max-idle-time: 30m
